[package]
name = "orca"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
csv = "1.3.1"
fixedbitset = "0.5.7"
petgraph = "0.6.5"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false
