use std::collections::{HashMap, HashSet};

use petgraph::{
    algo::is_isomorphic,
    graph::{Graph, NodeIndex},
    Undirected,
};

type Index = u32;
type MGraph = Graph<Atom, Bond, Undirected, Index>;

#[derive(Debug, Clone)]
pub enum Element {
    Hydrogen,
    Carbon,
    Nitrogen,
    Oxygen,
}

#[derive(Debug, Clone)]
pub struct Atom {
    element: Element,
    capacity: u32,
}

#[derive(Debug, Clone)]
pub enum Bond {
    Single,
    Double,
}

#[derive(Debug, Clone)]
pub struct Molecule {
    graph: MGraph,
}

impl Atom {
    pub fn new(element: Element) -> Self {
        Self {
            element,
            capacity: 0,
        }
    }
}

impl Molecule {
    /// Join self with other on `on`
    pub fn join(
        &self,
        other: &Molecule,
        on: impl IntoIterator<Item = (NodeIndex, NodeIndex)>,
    ) -> Option<Molecule> {
        let mut output_graph = self.clone();

        let mut v_set = HashSet::<NodeIndex>::new();
        let mut io_map = HashMap::<NodeIndex, NodeIndex>::new();

        for (u, v) in on.into_iter() {
            v_set.insert(v);
            io_map.insert(v, u);
        }

        for ix in other.graph.node_indices() {
            if !v_set.contains(&ix) {
                let w = other.graph.node_weight(ix).unwrap().clone();
                let out = output_graph.graph.add_node(w);
                io_map.insert(ix, out);
            }
        }

        for ix in other.graph.edge_indices() {
            let (u, v) = other.graph.edge_endpoints(ix).unwrap();
            let um = io_map.get(&u).unwrap();
            let vm = io_map.get(&v).unwrap();
            let w = other.graph.edge_weight(ix).unwrap().clone();

            output_graph.graph.add_edge(*um, *vm, w);
        }

        Some(output_graph)
    }

    pub fn is_isomorphic_to(&self, other: &Molecule) -> bool {
        is_isomorphic(&self.graph, &other.graph)
    }

    /// Split molecule on `on` and return an iterator over all possible molecule pairs generated by
    /// this split
    // pub fn split(
    //     &self,
    //     on: impl IntoIterator<Item = NodeIndex>,
    // ) -> Option<impl Iterator<Item = (Molecule, Molecule)>> {
    // }

    /// Iterator over every joinable set of n vertices in self
    // pub fn n_join_points(&self, n: usize) -> impl Iterator<Item = impl Iterator<Item = Index>> {}

    pub fn from_graph(g: MGraph) -> Self {
        Self { graph: g }
    }

    pub fn single_bond() -> Self {
        let mut g = Graph::default();
        let u = g.add_node(Atom {
            capacity: 4,
            element: Element::Carbon,
        });
        let v = g.add_node(Atom {
            capacity: 4,
            element: Element::Carbon,
        });
        g.add_edge(u, v, Bond::Single);
        Self { graph: g }
    }

    pub fn double_bond() -> Self {
        let mut g = Graph::default();
        let u = g.add_node(Atom {
            capacity: 4,
            element: Element::Carbon,
        });
        let v = g.add_node(Atom {
            capacity: 4,
            element: Element::Carbon,
        });
        g.add_edge(u, v, Bond::Double);
        Self { graph: g }
    }

    pub fn carbonyl() -> Self {
        let mut g = Graph::default();
        let u = g.add_node(Atom {
            capacity: 4,
            element: Element::Carbon,
        });
        let v = g.add_node(Atom {
            capacity: 2,
            element: Element::Oxygen,
        });
        g.add_edge(u, v, Bond::Double);
        Self { graph: g }
    }

    pub fn hydroxyl() -> Self {
        let mut g = Graph::default();
        let u = g.add_node(Atom {
            capacity: 4,
            element: Element::Carbon,
        });
        let v = g.add_node(Atom {
            capacity: 2,
            element: Element::Oxygen,
        });
        g.add_edge(u, v, Bond::Single);
        Self { graph: g }
    }
}

mod tests {
    use super::*;

    #[test]
    fn join_carbonyl_hydroxyl() {
        let c = Molecule::carbonyl();
        let h = Molecule::hydroxyl();
        let j = c
            .join(&h, [(NodeIndex::new(0), NodeIndex::new(0))])
            .unwrap();

        let mut g = Graph::default();
        let u = g.add_node(Atom {
            capacity: 4,
            element: Element::Carbon,
        });
        let v = g.add_node(Atom {
            capacity: 2,
            element: Element::Oxygen,
        });
        let w = g.add_node(Atom {
            capacity: 2,
            element: Element::Oxygen,
        });
        g.add_edge(u, v, Bond::Single);
        g.add_edge(u, w, Bond::Double);

        assert!(j.is_isomorphic_to(&Molecule { graph: g }));
    }
}
